# Generated by Django 4.2 on 2023-05-07 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='rated_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
